services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  ingest:
    build: .
    env_file:
      - .env
    command: python main.py
    profiles:
      - job
    volumes:
      - ./data:/app/data
